import { Bicycle, User, RentalLog } from '@/types';

export const mockBicycles: Bicycle[] = [
  {
    id: '1',
    deviceId: 'BIKE-001',
    status: 'available',
    location: { lat: 14.5995, lng: 120.9842 },
    battery: 85,
    lastUpdate: new Date().toISOString(),
  },
  {
    id: '2',
    deviceId: 'BIKE-002',
    status: 'in-use',
    location: { lat: 14.6010, lng: 120.9850 },
    battery: 62,
    lastUpdate: new Date().toISOString(),
  },
  {
    id: '3',
    deviceId: 'BIKE-003',
    status: 'available',
    location: { lat: 14.5980, lng: 120.9830 },
    battery: 94,
    lastUpdate: new Date().toISOString(),
  },
  {
    id: '4',
    deviceId: 'BIKE-004',
    status: 'offline',
    location: { lat: 14.5970, lng: 120.9860 },
    battery: 12,
    lastUpdate: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: '5',
    deviceId: 'BIKE-005',
    status: 'maintenance',
    location: { lat: 14.6000, lng: 120.9845 },
    battery: 0,
    lastUpdate: new Date(Date.now() - 7200000).toISOString(),
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@university.edu',
    rfidTag: 'RFID-1001',
    status: 'active',
    registeredAt: '2025-01-15T08:00:00Z',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@university.edu',
    rfidTag: 'RFID-1002',
    status: 'active',
    registeredAt: '2025-01-16T09:30:00Z',
  },
  {
    id: '3',
    name: 'Mike Johnson',
    email: 'mike.j@university.edu',
    rfidTag: 'RFID-1003',
    status: 'inactive',
    registeredAt: '2025-01-10T14:20:00Z',
  },
  {
    id: '4',
    name: 'Sarah Williams',
    email: 'sarah.w@university.edu',
    rfidTag: 'RFID-1004',
    status: 'active',
    registeredAt: '2025-01-18T11:00:00Z',
  },
];

export const mockRentalLogs: RentalLog[] = [
  {
    id: '1',
    userId: '1',
    userName: 'John Doe',
    bicycleId: '2',
    deviceId: 'BIKE-002',
    startTime: new Date(Date.now() - 1800000).toISOString(),
    status: 'ongoing',
  },
  {
    id: '2',
    userId: '2',
    userName: 'Jane Smith',
    bicycleId: '1',
    deviceId: 'BIKE-001',
    startTime: new Date(Date.now() - 7200000).toISOString(),
    endTime: new Date(Date.now() - 3600000).toISOString(),
    duration: '1h 0m',
    status: 'completed',
  },
  {
    id: '3',
    userId: '4',
    userName: 'Sarah Williams',
    bicycleId: '3',
    deviceId: 'BIKE-003',
    startTime: new Date(Date.now() - 14400000).toISOString(),
    endTime: new Date(Date.now() - 10800000).toISOString(),
    duration: '1h 0m',
    status: 'completed',
  },
  {
    id: '4',
    userId: '1',
    userName: 'John Doe',
    bicycleId: '5',
    deviceId: 'BIKE-005',
    startTime: new Date(Date.now() - 86400000).toISOString(),
    endTime: new Date(Date.now() - 82800000).toISOString(),
    duration: '1h 0m',
    status: 'completed',
  },
];